POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{"username": "lolo", "password": "Pass1234!", "email": "joj3@mail.com" , "first_name": "lolol3", "last_name":"nooy", "role": "nurse"}

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "email": "joj3@mail.com", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json 
Authorization: Token ad8a73033df0340923b3892f362e04631038d900


###
POST http://127.0.0.1:8000/api/patients/patients/
Content-Type:  application/json 
Authorization: Token 409ad63e44933267df0eebe5610a09e648d7f049

    {"name": "Joshua Kol",
      "email": "gloria@gmail.com",
      "address": "bola  street, Lagos",
      "profileImage": null,
      "scan": null,
      "phone": "+23408023397367",
      "dateOfBirth": "2002-04-06"
      }

###      
GET http://127.0.0.1:8000/api/patients/patients/2
Content-Type:  application/json 
Authorization: Token 409ad63e44933267df0eebe5610a09e648d7f049

###
PATCH   http://127.0.0.1:8000/api/127.0.0.1:8000/api/patients/patients/2/
Content-Type:  application/json 
Authorization: Token 409ad63e44933267df0eebe5610a09e648d7f049

    {
      "name": "Maria Carey2",

    }


###
GET http://127.0.0.1:8000/api/patients/patients/2
Content-Type:  application/json
Authorization: Token 1fc2cd971fea2887c73ff6c3bb7b4dcbc348a4cf

###
GET  http://127.0.0.1:8000/api/patients/1
Content-Type:  application/json
Authorization: Token e43d6002368c9c49a5be7c32a95d69f659e1d6b7

###
GET http://127.0.0.1:8000/api/specialisations/specialisations/
Content-Type:  application/json
Authorization: Token 409ad63e44933267df0eebe5610a09e648d7f049

###
POST http://127.0.0.1:8000/api/specialisations/
Content-Type:  application/json
Authorization: Token e43d6002368c9c49a5be7c32a95d69f659e1d6b7

  {
    "name": "optometrist",
  },



###
PATCH  http://127.0.0.1:8000/api/specialisations/specialisations/2
Content-Type:  application/json
Authorization: Token e43d6002368c9c49a5be7c32a95d69f659e1d6b7

  {
    "name": "oncologist",
  },

###
DELETE http://127.0.0.1:8000/api/patients/patients/2/
Content-Type: application/json
Authorization: Token 409ad63e44933267df0eebe5610a09e648d7f049

