# Generated by Django 4.2.3 on 2023-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurseID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'nurses',
            },
        ),
    ]
