# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physicians', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacies', '0001_initial'),
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('drugName', models.CharField(max_length=200)),
                ('prescription', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('diagnoses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='checkup.checkupdetail')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physicians.physician')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'prescriptions',
            },
        ),
    ]
