# Generated by Django 4.2.3 on 2023-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_role',
            field=models.CharField(blank=True, default='patient', max_length=255, null=True),
        ),
    ]
