# Generated by Django 4.2.3 on 2023-07-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('doctorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('contact', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=100)),
                ('specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialisations.specialisation')),
            ],
            options={
                'verbose_name_plural': 'doctors',
            },
        ),
    ]
