# Generated by Django 4.2.3 on 2023-07-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physicians', '0002_physician_createdat_physician_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupDetail',
            fields=[
                ('diagnosesID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnoses', models.TextField()),
                ('doctorRemark', models.TextField()),
                ('locatiom', models.CharField(max_length=200)),
                ('prescription', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physicians.physician')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
            },
        ),
    ]
