# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupDetail',
            fields=[
                ('diagnosesID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnoses', models.TextField()),
                ('doctorRemark', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('prescription', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
            },
        ),
    ]
