# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physicians', '0001_initial'),
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkupdetail',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physicians.physician'),
        ),
    ]
