# Generated by Django 4.2.3 on 2023-07-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VITALSIGN',
            fields=[
                ('vitalSignId', models.AutoField(primary_key=True, serialize=False)),
                ('bloodPressure', models.IntegerField()),
                ('weight', models.CharField(max_length=200)),
                ('pulseRate', models.FloatField()),
                ('height', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('bloodSugar', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.patients')),
                ('specialisatiion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialisations.specialisation')),
            ],
        ),
    ]
